import type { ComponentType, ReactNode } from "react";
import {
  AudioWaveform,
  FileAudio,
  Image,
  FileMinus,
  FileImage,
  QrCode,
  FileText,
  Table,
  Braces,
  FileCode2,
  FileJson,
  Key,
  Fingerprint,
  SearchCode,
  Terminal,
  Type,
  Replace,
  Hash,
  ShieldAlert,
  Scale,
  Lock,
  Box,
  ListTree,
  Code,
  MonitorSmartphone,
  Database,
  DatabaseZap,
  DatabaseBackup,
  Palette,
  Pipette,
  PaintBucket,
  Paintbrush,
  Network,
  Server,
  ImagePlus,
  AppWindow,
  Settings,
  Clock,
  CalendarDays,
  Link2,
  LayoutTemplate,
  Map,
  Ruler,
  AlignLeft,
  Youtube,
  Instagram,
  Facebook,
  Music2,
  Keyboard,
  Spline,
  Webhook,
} from "lucide-react";

// Named imports only (not `import * as`) so tree-shaking keeps unused
// lucide-react icons out of Home's eager bundle. Add new icons here as
// registry entries need them.
const ICONS: Record<string, ComponentType> = {
  AudioWaveform,
  FileAudio,
  Image,
  FileMinus,
  FileImage,
  QrCode,
  FileText,
  Table,
  Braces,
  FileCode2,
  FileJson,
  Key,
  Fingerprint,
  SearchCode,
  Terminal,
  Type,
  Replace,
  Hash,
  ShieldAlert,
  Scale,
  Lock,
  Box,
  ListTree,
  Code,
  MonitorSmartphone,
  Database,
  DatabaseZap,
  DatabaseBackup,
  Palette,
  Pipette,
  PaintBucket,
  Paintbrush,
  Network,
  Server,
  ImagePlus,
  AppWindow,
  Settings,
  Clock,
  CalendarDays,
  Link2,
  LayoutTemplate,
  Map,
  Ruler,
  AlignLeft,
  Youtube,
  Instagram,
  Facebook,
  Music2,
  Keyboard,
  Spline,
  Webhook,
};

export function resolveIcon(name?: string): ReactNode {
  const Icon = name ? ICONS[name] : undefined;
  if (!Icon) {
    if (import.meta.env.DEV) {
      console.warn(`resolveIcon: unknown icon "${name}"`);
    }
    return null;
  }
  return <Icon />;
}
