export interface ToolDefinition {
  id: string;
  name: string;
  category: string;
  description: string;
  route: string;
  status: 'stable' | 'beta' | 'deprecated';
  keywords: string[];
  iconName?: string;
}

// Display order for homepage categories. Categories not listed here fall back
// to appearing after these, sorted alphabetically (see src/pages/Home.tsx).
// "Recommended" is a synthetic category computed at render time from usage
// stats — it must never appear here.
export const CATEGORY_ORDER: string[] = [
  "Social Media Downloader",
  "Everyday Tools",
  "Video & Audio",
  "Images",
  "File Conversion",
  "PDF Tools",
  "Developer",
  "DevOps & SEO",
  "Database Tools",
  "Color Tools",
  "API Tools",
  "Business",
];

// Single source of truth for tool metadata (name, description, category,
// route, keywords, icon). Consumed by src/pages/Home.tsx (homepage grid +
// search) and src/lib/toolsCatalog.ts (admin dashboard toggle list).
//
// IMPORTANT — ordering contract: entries are grouped by category, and within
// a category the insertion order below IS the display order (Object.values()
// preserves insertion order). Do NOT alphabetize this file — several
// categories have a deliberate, non-alphabetical order.
//
// IMPORTANT — never rename an entry's `name` once shipped: the stable tool id
// used for admin disable-toggles and usage analytics (see src/lib/toolId.ts)
// is derived from `name`, not from the `id` key below, and existing Supabase
// rows are keyed off the current name.
export const toolRegistry: Record<string, ToolDefinition> = {
  // --- Social Media Downloader ---
  youtubeDownloader: {
    id: "youtubeDownloader",
    name: "YouTube Downloader",
    category: "Social Media Downloader",
    description: "Download YouTube videos, Shorts & audio",
    route: "/tools/social-downloader?platform=youtube",
    status: "stable",
    keywords: ["youtube", "yt", "download", "video", "shorts", "mp4", "mp3", "music", "social"],
    iconName: "Youtube",
  },
  instagramDownloader: {
    id: "instagramDownloader",
    name: "Instagram Downloader",
    category: "Social Media Downloader",
    description: "Save Reels, posts & video clips",
    route: "/tools/social-downloader?platform=instagram",
    status: "stable",
    keywords: ["instagram", "ig", "reel", "reels", "post", "download", "video", "social"],
    iconName: "Instagram",
  },
  tiktokDownloader: {
    id: "tiktokDownloader",
    name: "TikTok Downloader",
    category: "Social Media Downloader",
    description: "Download TikTok videos without watermark",
    route: "/tools/social-downloader?platform=tiktok",
    status: "stable",
    keywords: ["tiktok", "tik tok", "download", "video", "watermark", "social", "clip"],
    iconName: "Music2",
  },
  facebookDownloader: {
    id: "facebookDownloader",
    name: "Facebook Downloader",
    category: "Social Media Downloader",
    description: "Save Facebook videos, Reels & watch clips",
    route: "/tools/social-downloader?platform=facebook",
    status: "stable",
    keywords: ["facebook", "fb", "reel", "watch", "download", "video", "social"],
    iconName: "Facebook",
  },
  xDownloader: {
    id: "xDownloader",
    name: "X (Twitter) Downloader",
    category: "Social Media Downloader",
    description: "Download videos from X posts",
    route: "/tools/social-downloader?platform=x",
    status: "stable",
    keywords: ["x", "twitter", "download", "video", "post", "tweet", "social"],
    iconName: "MonitorSmartphone",
  },

  // --- Everyday Tools ---
  wordCounter: {
    id: "wordCounter",
    name: "Word Counter",
    category: "Everyday Tools",
    description: "Count words, characters, and sentences",
    route: "/tools/word-counter",
    status: "stable",
    keywords: ["word", "character", "count", "counter", "text", "sentences", "paragraphs"],
    iconName: "AlignLeft",
  },
  caseConverter: {
    id: "caseConverter",
    name: "Case Converter",
    category: "Everyday Tools",
    description: "Convert to UPPERCASE, lowercase, CamelCase, etc",
    route: "/tools/case-converter",
    status: "stable",
    keywords: ["case", "convert", "uppercase", "lowercase", "text", "camelcase", "snake", "title"],
    iconName: "Type",
  },
  unitConverter: {
    id: "unitConverter",
    name: "Unit Converter",
    category: "Everyday Tools",
    description: "Convert length, weight, and temperature",
    route: "/tools/unit-converter",
    status: "stable",
    keywords: ["unit", "convert", "length", "weight", "temperature", "meters", "kilograms", "farenheit"],
    iconName: "Ruler",
  },
  timezoneConverter: {
    id: "timezoneConverter",
    name: "Timezone Converter",
    category: "Everyday Tools",
    description: "Convert times between any time zones",
    route: "/tools/timezone",
    status: "stable",
    keywords: ["timezone", "time zone", "convert", "utc", "gmt", "world clock", "meeting", "time"],
    iconName: "Clock",
  },
  passwordStrength: {
    id: "passwordStrength",
    name: "Password Strength",
    category: "Everyday Tools",
    description: "Check how secure your password is",
    route: "/tools/password",
    status: "stable",
    keywords: ["password", "strength", "secure", "check", "entropy", "safety", "security"],
    iconName: "ShieldAlert",
  },
  fancyFont: {
    id: "fancyFont",
    name: "Fancy Font Generator",
    category: "Everyday Tools",
    description: "Copyable unicode text styles for bios & posts",
    route: "/tools/fancy-font",
    status: "stable",
    keywords: ["font", "fancy", "text", "style", "unicode", "copy", "paste", "bio", "instagram"],
    iconName: "Type",
  },
  qrCode: {
    id: "qrCode",
    name: "QR Code Generator",
    category: "Everyday Tools",
    description: "High-res, lossless QR codes",
    route: "/tools/qrcode",
    status: "stable",
    keywords: ["qr", "qrcode", "barcode", "generate", "code"],
    iconName: "QrCode",
  },

  // --- Video & Audio ---
  videoToAudio: {
    id: "videoToAudio",
    name: "Convert Video to Audio",
    category: "Video & Audio",
    description: "Extract MP3 or WAV from any clip",
    route: "/tools/video-to-audio",
    status: "stable",
    keywords: ["mp4", "mp3", "wav", "extract", "audio", "video"],
    iconName: "AudioWaveform",
  },
  audioConvert: {
    id: "audioConvert",
    name: "Convert Audio",
    category: "Video & Audio",
    description: "Between MP3, WAV, AAC and OGG",
    route: "/tools/audio-convert",
    status: "stable",
    keywords: ["mp3", "wav", "aac", "ogg", "flac", "audio", "convert"],
    iconName: "FileAudio",
  },
  compressAudio: {
    id: "compressAudio",
    name: "Compress Audio",
    category: "Video & Audio",
    description: "Reduce file sizes instantly",
    route: "/tools/compress-audio",
    status: "stable",
    keywords: ["audio", "compress", "size", "bitrate", "mp3", "shrink", "reduce"],
    iconName: "FileMinus",
  },

  // --- Images ---
  ogImage: {
    id: "ogImage",
    name: "OpenGraph Image Generator",
    category: "Images",
    description: "Preview and generate OG cards",
    route: "/tools/og-image",
    status: "stable",
    keywords: ["og", "opengraph", "social", "twitter", "facebook", "card", "meta", "generate"],
    iconName: "MonitorSmartphone",
  },
  imageConvert: {
    id: "imageConvert",
    name: "Convert Image",
    category: "Images",
    description: "PNG, JPG, WebP and AVIF",
    route: "/tools/image-convert",
    status: "stable",
    keywords: ["png", "jpg", "jpeg", "webp", "avif", "image", "convert"],
    iconName: "Image",
  },
  imageCompress: {
    id: "imageCompress",
    name: "Compress Image",
    category: "Images",
    description: "Smaller files, sharp detail",
    route: "/tools/image-compress",
    status: "stable",
    keywords: ["compress", "shrink", "reduce", "optimize", "image", "size"],
    iconName: "FileMinus",
  },
  imageResize: {
    id: "imageResize",
    name: "Resize Image",
    category: "Images",
    description: "Set exact pixel dimensions",
    route: "/tools/image-resize",
    status: "stable",
    keywords: ["resize", "scale", "crop", "dimensions", "width", "height", "image"],
    iconName: "FileImage",
  },
  favicon: {
    id: "favicon",
    name: "Favicon Generator",
    category: "Images",
    description: "Generate multi-size favicons",
    route: "/tools/favicon",
    status: "stable",
    keywords: ["favicon", "icon", "website", "generate", "ico"],
    iconName: "AppWindow",
  },
  svgTool: {
    id: "svgTool",
    name: "SVG Viewer & Converter",
    category: "Images",
    description: "Preview and convert SVGs",
    route: "/tools/svg",
    status: "stable",
    keywords: ["svg", "vector", "convert", "viewer", "png", "jpg", "image"],
    iconName: "ImagePlus",
  },

  // --- File Conversion ---
  spreadsheetConverter: {
    id: "spreadsheetConverter",
    name: "Spreadsheet Converter",
    category: "File Conversion",
    description: "Convert between XLSX, XLS, CSV, ODS, JSON",
    route: "/tools/spreadsheet",
    status: "stable",
    keywords: ["excel", "csv", "xls", "xlsx", "ods", "json", "sheet", "spreadsheet", "convert"],
    iconName: "Table",
  },
  documentConverter: {
    id: "documentConverter",
    name: "Document Converter",
    category: "File Conversion",
    description: "Word, text, HTML and PDF interchange",
    route: "/tools/document",
    status: "stable",
    keywords: ["word", "docx", "doc", "pdf", "txt", "html", "markdown", "document", "convert"],
    iconName: "FileText",
  },
  pptToPdf: {
    id: "pptToPdf",
    name: "PowerPoint to PDF",
    category: "File Conversion",
    description: "Convert .pptx slides to PDF in your browser",
    route: "/tools/ppt-pdf",
    status: "stable",
    keywords: ["powerpoint", "ppt", "pptx", "pdf", "slides", "presentation", "convert"],
    iconName: "FileText",
  },
  pdfToWord: {
    id: "pdfToWord",
    name: "PDF to Word",
    category: "File Conversion",
    description: "Extract PDF text into an editable doc",
    route: "/tools/pdf-word",
    status: "stable",
    keywords: ["pdf", "word", "docx", "convert", "document"],
    iconName: "FileText",
  },

  // --- PDF Tools ---
  mergePdf: {
    id: "mergePdf",
    name: "Merge PDF",
    category: "PDF Tools",
    description: "Combine multiple PDFs into one",
    route: "/tools/merge-pdf",
    status: "stable",
    keywords: ["pdf", "merge", "combine", "join", "concatenate"],
    iconName: "FileText",
  },
  splitPdf: {
    id: "splitPdf",
    name: "Split PDF",
    category: "PDF Tools",
    description: "Extract pages or split into files",
    route: "/tools/split-pdf",
    status: "stable",
    keywords: ["pdf", "split", "extract", "pages", "separate"],
    iconName: "FileText",
  },
  compressPdf: {
    id: "compressPdf",
    name: "Compress PDF",
    category: "PDF Tools",
    description: "Reduce PDF file size",
    route: "/tools/compress-pdf",
    status: "stable",
    keywords: ["pdf", "compress", "shrink", "reduce", "size", "optimize"],
    iconName: "FileMinus",
  },
  organizePdf: {
    id: "organizePdf",
    name: "Organize PDF",
    category: "PDF Tools",
    description: "Reorder and delete pages visually",
    route: "/tools/organize-pdf",
    status: "stable",
    keywords: ["pdf", "organize", "reorder", "delete", "pages", "rearrange", "rotate"],
    iconName: "AppWindow",
  },
  imageToPdf: {
    id: "imageToPdf",
    name: "Image to PDF",
    category: "PDF Tools",
    description: "Combine JPG and PNG into a PDF",
    route: "/tools/image-to-pdf",
    status: "stable",
    keywords: ["image", "jpg", "png", "pdf", "convert", "combine", "photo"],
    iconName: "Image",
  },
  pdfToImage: {
    id: "pdfToImage",
    name: "PDF to Image",
    category: "PDF Tools",
    description: "Export PDF pages as PNG or JPG",
    route: "/tools/pdf-to-image",
    status: "stable",
    keywords: ["pdf", "image", "png", "jpg", "convert", "export", "pages"],
    iconName: "FileImage",
  },

  // --- Developer ---
  testDataGenerator: {
    id: "testDataGenerator",
    name: "Test Data Generator",
    category: "Developer",
    description: "Generate fake JSON/CSV data",
    route: "/tools/test-data",
    status: "stable",
    keywords: ["fake", "mock", "test", "data", "json", "csv", "generator", "faker"],
    iconName: "Settings",
  },
  jsonFormatter: {
    id: "jsonFormatter",
    name: "JSON Formatter",
    category: "Developer",
    description: "Prettify, minify and validate",
    route: "/tools/json",
    status: "stable",
    keywords: ["json", "format", "prettify", "minify", "validate", "lint", "beautify"],
    iconName: "Braces",
  },
  jsonToTs: {
    id: "jsonToTs",
    name: "JSON to TypeScript",
    category: "Developer",
    description: "Convert JSON to TS interfaces",
    route: "/tools/json-to-ts",
    status: "stable",
    keywords: ["json", "ts", "typescript", "interface", "type", "convert", "generator"],
    iconName: "FileCode2",
  },
  jsonToZod: {
    id: "jsonToZod",
    name: "JSON to Zod",
    category: "Developer",
    description: "Convert JSON to Zod schema",
    route: "/tools/json-to-zod",
    status: "stable",
    keywords: ["json", "zod", "schema", "validation", "typescript", "convert"],
    iconName: "FileJson",
  },
  jwtDecoder: {
    id: "jwtDecoder",
    name: "JWT Decoder",
    category: "Developer",
    description: "Decode JSON Web Tokens",
    route: "/tools/jwt",
    status: "stable",
    keywords: ["jwt", "token", "decode", "parse", "json web token"],
    iconName: "Key",
  },
  jwtGenerator: {
    id: "jwtGenerator",
    name: "JWT Generator",
    category: "Developer",
    description: "Generate JSON Web Tokens",
    route: "/tools/jwt-generator",
    status: "stable",
    keywords: ["jwt", "token", "generate", "create", "sign", "json web token"],
    iconName: "Key",
  },
  uuid: {
    id: "uuid",
    name: "UUID Generator",
    category: "Developer",
    description: "Generate universally unique identifiers",
    route: "/tools/uuid",
    status: "stable",
    keywords: ["uuid", "guid", "generate", "v4", "v1", "identifier"],
    iconName: "Fingerprint",
  },
  urlEncoder: {
    id: "urlEncoder",
    name: "URL Encoder / Decoder",
    category: "Developer",
    description: "Encode or decode URLs",
    route: "/tools/url-encoder",
    status: "stable",
    keywords: ["url", "encode", "decode", "uri", "percent", "escape"],
    iconName: "Link2",
  },
  cronGenerator: {
    id: "cronGenerator",
    name: "Cron Expression Generator",
    category: "Developer",
    description: "Decode and generate cron jobs",
    route: "/tools/cron",
    status: "stable",
    keywords: ["cron", "schedule", "job", "time", "generate", "parse", "expression"],
    iconName: "CalendarDays",
  },
  timestampConverter: {
    id: "timestampConverter",
    name: "Timestamp Converter",
    category: "Developer",
    description: "Convert Unix time to human date",
    route: "/tools/timestamp",
    status: "stable",
    keywords: ["timestamp", "unix", "epoch", "time", "date", "convert", "human readable"],
    iconName: "Clock",
  },
  markdownPreviewer: {
    id: "markdownPreviewer",
    name: "Markdown Previewer",
    category: "Developer",
    description: "Live Markdown formatting preview",
    route: "/tools/markdown",
    status: "stable",
    keywords: ["md", "markdown", "preview", "editor", "format", "live"],
    iconName: "LayoutTemplate",
  },
  loremIpsum: {
    id: "loremIpsum",
    name: "Lorem Ipsum Generator",
    category: "Developer",
    description: "Generate random placeholder text",
    route: "/tools/lorem",
    status: "stable",
    keywords: ["lorem", "ipsum", "placeholder", "text", "dummy", "generator"],
    iconName: "FileText",
  },
  regexTester: {
    id: "regexTester",
    name: "Regex Tester",
    category: "Developer",
    description: "Test and debug regular expressions",
    route: "/tools/regex",
    status: "stable",
    keywords: ["regex", "regular expression", "test", "match", "replace", "pattern"],
    iconName: "SearchCode",
  },
  gitignore: {
    id: "gitignore",
    name: ".gitignore Generator",
    category: "Developer",
    description: "Create gitignores for any stack",
    route: "/tools/gitignore",
    status: "stable",
    keywords: ["git", "gitignore", "ignore", "repo", "repository", "generate"],
    iconName: "FileText",
  },
  curlToFetch: {
    id: "curlToFetch",
    name: "Curl to Fetch",
    category: "Developer",
    description: "Convert curl commands to fetch API",
    route: "/tools/curl-to-fetch",
    status: "stable",
    keywords: ["curl", "fetch", "http", "request", "convert", "api"],
    iconName: "Terminal",
  },
  base64: {
    id: "base64",
    name: "Base64 Encode / Decode",
    category: "Developer",
    description: "Text and small files",
    route: "/tools/base64",
    status: "stable",
    keywords: ["base64", "encode", "decode", "text", "format", "convert"],
    iconName: "Replace",
  },
  hashGenerator: {
    id: "hashGenerator",
    name: "Hash Generator",
    category: "Developer",
    description: "SHA-256, SHA-1 and MD5",
    route: "/tools/hash",
    status: "stable",
    keywords: ["hash", "md5", "sha1", "sha256", "sha512", "crypto", "generate"],
    iconName: "Hash",
  },
  license: {
    id: "license",
    name: "License Generator",
    category: "Developer",
    description: "Generate MIT, Apache, GPL licenses",
    route: "/tools/license",
    status: "stable",
    keywords: ["license", "mit", "apache", "gpl", "open source", "generate"],
    iconName: "Scale",
  },
  bcrypt: {
    id: "bcrypt",
    name: "bcrypt Generator",
    category: "Developer",
    description: "Generate bcrypt password hashes",
    route: "/tools/bcrypt",
    status: "stable",
    keywords: ["bcrypt", "hash", "password", "crypto", "generate", "compare"],
    iconName: "Lock",
  },

  // --- DevOps & SEO ---
  sitemap: {
    id: "sitemap",
    name: "Sitemap Generator",
    category: "DevOps & SEO",
    description: "Generate XML sitemaps",
    route: "/tools/sitemap",
    status: "stable",
    keywords: ["sitemap", "xml", "seo", "generate", "url", "bot"],
    iconName: "Map",
  },
  dockerfile: {
    id: "dockerfile",
    name: "Dockerfile Generator",
    category: "DevOps & SEO",
    description: "Generate Dockerfiles for Node, Python, Go",
    route: "/tools/dockerfile",
    status: "stable",
    keywords: ["docker", "dockerfile", "container", "generate", "image", "devops"],
    iconName: "Box",
  },
  changelog: {
    id: "changelog",
    name: "Changelog Generator",
    category: "DevOps & SEO",
    description: "Create standard changelogs",
    route: "/tools/changelog",
    status: "stable",
    keywords: ["changelog", "release", "notes", "version", "history", "generate"],
    iconName: "ListTree",
  },
  metadataGenerator: {
    id: "metadataGenerator",
    name: "Metadata Generator",
    category: "DevOps & SEO",
    description: "Generate OpenGraph meta tags",
    route: "/tools/metadata",
    status: "stable",
    keywords: ["meta", "tags", "seo", "html", "head", "generate", "opengraph"],
    iconName: "Code",
  },

  // --- Database Tools ---
  sqlFormatter: {
    id: "sqlFormatter",
    name: "SQL Query Formatter",
    category: "Database Tools",
    description: "Beautify SQL statements",
    route: "/tools/sql-formatter",
    status: "stable",
    keywords: ["sql", "format", "beautify", "query", "database", "postgres", "mysql"],
    iconName: "Database",
  },
  mongoFormatter: {
    id: "mongoFormatter",
    name: "MongoDB Query Formatter",
    category: "Database Tools",
    description: "Format MongoDB queries",
    route: "/tools/mongo-formatter",
    status: "stable",
    keywords: ["mongo", "mongodb", "format", "query", "nosql", "database", "beautify"],
    iconName: "DatabaseZap",
  },
  jsonToSql: {
    id: "jsonToSql",
    name: "JSON to SQL Insert",
    category: "Database Tools",
    description: "Convert JSON array to SQL inserts",
    route: "/tools/json-to-sql",
    status: "stable",
    keywords: ["json", "sql", "insert", "convert", "database", "query", "table"],
    iconName: "DatabaseBackup",
  },

  // --- Color Tools ---
  hexToRgb: {
    id: "hexToRgb",
    name: "HEX to RGB",
    category: "Color Tools",
    description: "Convert HEX colors to RGB",
    route: "/tools/hex-rgb",
    status: "stable",
    keywords: ["hex", "rgb", "color", "convert", "css"],
    iconName: "Palette",
  },
  rgbToHsl: {
    id: "rgbToHsl",
    name: "RGB to HSL",
    category: "Color Tools",
    description: "Convert RGB colors to HSL",
    route: "/tools/rgb-hsl",
    status: "stable",
    keywords: ["rgb", "hsl", "color", "convert", "css"],
    iconName: "Pipette",
  },
  gradient: {
    id: "gradient",
    name: "Gradient Generator",
    category: "Color Tools",
    description: "Create CSS gradients",
    route: "/tools/gradient",
    status: "stable",
    keywords: ["gradient", "css", "color", "generator", "background", "linear", "radial"],
    iconName: "PaintBucket",
  },
  colorPalette: {
    id: "colorPalette",
    name: "Color Palette",
    category: "Color Tools",
    description: "Generate color schemes",
    route: "/tools/palette",
    status: "stable",
    keywords: ["color", "palette", "scheme", "generator", "theme", "combinations", "analogous", "complementary"],
    iconName: "Paintbrush",
  },

  // --- API Tools ---
  restApi: {
    id: "restApi",
    name: "REST API Tester",
    category: "API Tools",
    description: "Test HTTP requests",
    route: "/tools/rest-api",
    status: "stable",
    keywords: ["api", "rest", "http", "fetch", "tester", "postman", "client", "request"],
    iconName: "Network",
  },
  httpHeaders: {
    id: "httpHeaders",
    name: "HTTP Header Viewer",
    category: "API Tools",
    description: "View HTTP request and response headers",
    route: "/tools/http-headers",
    status: "stable",
    keywords: ["http", "headers", "request", "response", "viewer", "sniff", "api"],
    iconName: "Server",
  },

  // --- Business ---
  invoice: {
    id: "invoice",
    name: "Invoice Generator",
    category: "Business",
    description: "Create and print beautiful invoices",
    route: "/tools/invoice",
    status: "stable",
    keywords: ["invoice", "bill", "receipt", "generate", "pdf", "print", "business"],
    iconName: "FileText",
  },
};
